import os

from dotenv import load_dotenv
# Load environment variables for secrets
load_dotenv(".env")
QDRANT_URL = os.getenv("QDRANT_URL")
QDRANT_API_KEY = os.getenv("QDRANT_KEY")
COLLECTION_NAME = "PWD_SENTENCE_TRANSFORMERS"
MODEL_NAME = "sentence-transformers/all-MiniLM-L6-v2"
AZURE_OPENAI_ENDPOINT = os.getenv("AZURE_OPENAI_ENDPOINT")
AZURE_OPENAI_API_KEY = os.getenv("AZURE_OPENAI_API_KEY")
AZURE_OPENAI_DEPLOYMENT_ID = os.getenv("AZURE_OPENAI_DEPLOYMENT_NAME")
OPENAI_API_VERSION = os.getenv("OPENAI_API_VERSION")

COSMOSDB_ENDPOINT= os.getenv("COSMOSDB_ENDPOINT")
COSMOSDB_KEY= os.getenv("COSMOSDB_KEY")
COSMOSDB_DATABASE_NAME= os.getenv("COSMOSDB_DATABASE_NAME")
COSMOSDB_CONTAINER_NAME= os.getenv("COSMOSDB_CONTAINER_NAME")
COSMOSDB_CONTAINER_NAME_CONVERSATIONS= os.getenv("COSMOSDB_CONTAINER_NAME_CONVERSATIONS")
COSMOSDB_CONTAINER_NAME_CONVERSATIONS_HEADER = os.getenv("COSMOSDB_CONTAINER_NAME_CONVERSATIONS_HEADER")
COSMOSDB_CONTAINER_NAME_CONVERSATIONS_CATEGORY = os.getenv("COSMOSDB_CONTAINER_NAME_CATEGORY")
